name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./test -s -r compact -d yes
      
    - name: Test_median
      working-directory: ${{github.workspace}}/build
      run: ./test -c median
  

    - name: day1
      working-directory: ${{github.workspace}}/build
      run: ./2021/day01/day01 < ../2021/day01/data.txt
      

    - name: day5
      working-directory: ${{github.workspace}}/build
      run: ./2021/day05/day05 < ../2021/day05/data.txt
    
    - name: day6
      working-directory: ${{github.workspace}}/build
      run: ./2021/day06/day06
    
     - name: day7
      working-directory: ${{github.workspace}}/build
      run: ./2021/day07/day07   
      
     - name: day8
      working-directory: ${{github.workspace}}/build
      run: ./2021/day08/day08
    
